---
- name: Playbook para instalar la pila LAMP en el Backend
  hosts: backend
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    # Actualizamos los repositorios para tener las últimas versiones de los paquetes
    - name: Actualizar los repositorios
      apt:
        update_cache: yes

    # Instalamos el servidor MySQL para la gestión de la base de datos
    - name: Instalar el sistema gestor de bases de datos MySQL
      apt:
        name: mysql-server
        state: present

    # Instalamos el módulo pymysql para poder gestionar MySQL desde el lenguaje Python
    - name: Instalar el módulo de pymysql
      apt:
        name: python3-pymysql
        state: present

    # Configuramos MySQL para que escuche en la IP privada especificada en las variables
    - name: Configurar MySQL para permitir conexiones desde cualquier interfaz
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: 127.0.0.1
        replace: "{{ db.BACKEND_PRIVATE_IP }}"

    # Aseguramos que MySQL acepte conexiones desde cualquier dirección IP en la red privada
    - name: Cambiar bind-address en mysqld.cnf
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address.*'
        replace: 'bind-address = 0.0.0.0'

    # Reiniciamos MySQL para aplicar los cambios de configuración
    - name: Reiniciar el servicio de base de datos
      service:
        name: mysql
        state: restarted