---
- name: Configurar Nginx como balanceador de carga
  hosts: balanceador
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    # Actualizamos los repositorios para tener las últimas versiones de los paquetes
    - name: Actualizar los repositorios
      apt:
        update_cache: yes

    # Actualizamos los paquetes del sistema, con 'dist' actualizamos los paquetes del sistema.
    - name: Actualizar los paquetes
      apt:
        upgrade: dist  

    # Instalamos Nginx 
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    # Copiamos la configuración personalizada del balanceador de carga desde mi template.
    - name: Copiar configuración de balanceador de carga
      template:
        src: ../templates/load_balancer.conf
        dest: /etc/nginx/sites-available/load_balancer.conf

    # Deshabilitamos la configuración por defecto de Nginx.
    - name: Deshabilitar el sitio por defecto de Nginx
      file:
        path: /etc/nginx/sites-enabled/default  # (ubicación del archivo de conf)
        state: absent  # Lo elimino

    # Sustituimos IP_FRONTEND_1 en la configuración con la IP real desde las variables.
    - name: Sustituir IP_FRONTEND_1 en la configuración
      replace:
        path: /etc/nginx/sites-available/load_balancer.conf
        regexp: 'balanceador.IP_FRONTEND_1'  
        replace: '{{ balanceador.IP_FRONTEND_1 }}'

    # Lo mismo para la IP_FRONTEND_2.
    - name: Sustituir IP_FRONTEND_2 en la configuración
      replace:
        path: /etc/nginx/sites-available/load_balancer.conf
        regexp: 'balanceador.IP_FRONTEND_2'
        replace: '{{ balanceador.IP_FRONTEND_2 }}'

    # Sustituimos el dominio de Let's Encrypt en la configuración del balanceador.
    - name: Sustituir LE_DOMAIN en la configuración
      replace:
        path: /etc/nginx/sites-available/load_balancer.conf
        regexp: 'certbot.domain'  # Buscamos el marcador de dominio.
        replace: '{{ certbot.domain }}'  # Lo reemplazo con el valor real.

    # Creamos un enlace simbólico para habilitar la configuración del balanceador de carga en Nginx.
    - name: Habilitar la configuración de Nginx
      file:
        src: /etc/nginx/sites-available/load_balancer.conf
        dest: /etc/nginx/sites-enabled/load_balancer.conf
        state: link

    # Deshabilitamos la configuración 000-default en Nginx.
    - name: Deshabilitar 000-default en Nginx
      file:
        path: /etc/nginx/sites-available/000-default.conf
        state: absent 

    # Finalmente, reiniciamos Nginx para que aplique los cambios.
    - name: Reiniciar Nginx
      systemd:
        name: nginx
        state: reloaded  # uso reload para recargar el servicio sin necesidad de reiniciarlo
